name: Testing with Pytest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests and generate XML report
        run: |
          export PYTHONPATH=.
          pytest --junitxml=pytest-report.xml
        continue-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-report.xml

      - name: Notify on success
        if: success()
        run: echo "✅ Pytest tests passed successfully!"

      - name: Notify on failure
        if: failure()
        run: echo "❌ Pytest tests failed!"
